public class LH_Keyword_Helper {
     
	public static String MISSING_ID = 'KeywordId/Campagin id is missing.';
    public static String SUCCESS_MSG = 'Success';
    public static String FAILURE_MSG = 'Failure';
    public static String ACCOUNT = 'Account';   //Keyword Controller
    public static String CONTACT = 'Contact';
    public static String LEAD = 'Lead';
    public static String CURRENCY_TYPE = 'Currency';
    public static String DATE_TYPE = 'Date';
    public static String NUMBER_TYPE = 'Number';
    public static String TEXT_TYPE = 'Text';
    public static String FINANCIAL_SERVICE_ACCOUNT = 'FinServ__IndividualId__c';
    
}